### ISSUE TITLE
Follow-up questions and hosting on Toolforge

### ISSUE THREAD

**Issue by eggpi** [Jain-Aditya/gsoc2018-microtask#1]
Hey, nice to see this repository! This does implement the microtask I had in mind, so well done! I have a couple follow-up questions you could think about, and hopefully they will help with your proposal.

No need to actually implement anything based on the questions, but I'll also suggest follow-up microtask at the end.

- If `index.php` were our server, we'd be querying PetScan every time a client navigates to the tool. As you may have seen, PetScan can often take very long to reply, especially for complex queries, which would make the tool unresponsive. How would you avoid that problem?
- The final tool will require some real-time features: for example, if I claim an article from a worklist, all other users looking at the same worklist should be able to see that. Broadly speaking, how would that be implemented? Where would we maintain the information about which articles are claimed or done and how would that propagate across all users?

I'm actually not very knowledgeable with PHP, but I'm totally fine with it if that's your preference. If you've never done it before, can you please set up a new tool on Toolforge and host this demo there, just so we get your SSH credentials working and figure out how to host a PHP server there?

Thanks, and do let me know if you have questions.

**Comment by Jain-Aditya** [comment]
Hi,
I have the following things in my mind for the above two issues:
1. Regarding the slowness of the PetScan API, we can use Memcached to temporarily store the response corresponding to a particular url (We can think of the right set of keys to be used while building the cache). Next time when the request comes, it will get the data from the cache instead of looking into the source API. This will fasten our tool.
2. We can use database for maintaining the state of the articles. To get the updated information, users will have to refresh the page every time (which is not really a real-time solution).
For displaying real time information, we can query the database at certain intervals of time or we can also think of using websockets? (Not sure which would be a better one)

I will be setting up the demo on toolforge shortly.

**Comment by eggpi** [comment]
Cool, thanks for the answers! Here's some comments.

Caching the PetScan results is a great idea, but if we're keeping the state of the articles in a database, could we just store the list of articles in the database too, after querying PetScan? That way we don't need Memcached at all.

Also, as we cache the PetScan results, we do need to go back and query it again at some point when the cache goes stale. If we do the query when a user accesses the tool, and the query takes (say) 2 minutes, it's still pretty bad user experience to wait 2 minutes for a page to load, even if only one user sees it at a time. Maybe we can avoid that problem too?

> To get the updated information, users will have to refresh the page every time (which is not really a real-time solution).

Yeah, it's not great to have to manually refresh the page to see new articles. But you've suggested a couple of techniques for sending article states to the client in real time, couldn't we use those for the list of articles too, without requiring a refresh?

> For displaying real time information, we can query the database at certain intervals of time or we can also think of using websockets? (Not sure which would be a better one)

Yes, good ideas! I think polling from Javascript is fine for our case, because:

- We don't need _really_ real time (milisecond latency), it's fine if it takes a few seconds to propagate the real time info.
- We do have an optional requirement in the Pabricator task of "Creating an API or export function designed for exporting information about the list for use in other tools"; if we define that API and poll it, it's easy to open it up to other clients without requiring them to use websocket.

What do you think?

**Comment by Jain-Aditya** [comment]
Hi,
I agree with storing the list of articles in a database instead of a cache corresponding to a worklist. Lets say in a campaign, a worklist is created named "Countries", the worklist creator will be providing certain set of keywords to get the list of articles. When he says "import" the articles, an API will be called which will internally query PetScan and stores the response from the PetScan into the database. This will be a one-time setup for creating a worklist. After the import is successful, the link to the worklist can be shared with others (The link will be a read API with worklist Id in the URL). 

>>We do have an optional requirement in the Pabricator task of "Creating an API or export function designed for exporting information about the list for use in other tools"; 

I guess this is the same as the read API which will be used to display the latest information?

**Comment by eggpi** [comment]
> Lets say in a campaign, a worklist is created named "Countries", the worklist creator will be providing certain set of keywords to get the list of articles.

If we receive keywords rather than a PetScan ID, the creator wouldn't be able to express worklists such as "Articles belonging to the two categories 'Jamaica' and 'All articles with unsourced statements', which have been edited in the past month by someone who is not a bot"

We can assume that worklist creators are experienced editors that know their way around PetScan, so it makes sense to give them the power to use it fully, at least for the initial version of the tool.

Creating "smart" worklists by keyword does seem like a cool idea, and if you want to explore that in your proposal, feel free to do so (explaining what use cases that helps with, and how you'd map keywords to PetScan queries). But I'd say we should start from receiving PetScan IDs as per the project description.

> This will be a one-time setup for creating a worklist.

The results of a PetScan query can change over time as categories change, or because it contains clauses like "edited in the last month" as in my example. Do we want to re-run the PetScan query at some point to refresh the worklist?

> The link will be a read API with worklist Id in the URL

I'm just nitpicking here, but: since the API would be consumed by other tools, it would probably return something more palatable than HTML, like JSON, so the link wouldn't be a direct link to the API.

> I guess this is the same as the read API which will be used to display the latest information?

Yeah, I think so. Or at least that's a good starting point.

**Comment by Jain-Aditya** [comment]
Alright I will go with PetScan ID for now for importing the list of articles. I will mention in the proposal about the "smart worklist" idea if time permits.

>>The results of a PetScan query can change over time as categories change, or because it contains clauses like "edited in the last month" as in my example. Do we want to re-run the PetScan query at some point to refresh the worklist?

We can have a background scheduler which will refresh the worklist at certain intervals of time. In addition, we can provide a refresh button on the worklist details page which can be used to get the updated list when desired.

>>since the API would be consumed by other tools, it would probably return something more palatable than HTML, like JSON, so the link wouldn't be a direct link to the API.

My bad! The link would be a webpage with that particular worklist details. The webpage will use our read API to display the list of articles along with their statuses.

**Comment by eggpi** [comment]
Cool, thank you! Please do try to launch your demo on Toolforge just so we get that initial setup out of the way, but other than that, looking forward to seeing your proposal :)

By the way, when you have a proposal draft we can take a look at, please consider putting it on a Google doc or something similar that the mentors can use to make inline comments and small edits for typos etc.

> We can have a background scheduler which will refresh the worklist at certain intervals of time.

Sounds good! [We can use Cron for that by the way](https://wikitech.wikimedia.org/wiki/Help:Toolforge/Grid#Scheduling_jobs_at_regular_intervals_with_cron).
